<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class LeaveTypeFullConfiguration extends Model
{
    use HasFactory;

    protected $table = 'leave_type_full_configurations';

    protected $fillable = [
        'puid',
        'corpid',
        'applicabilityType',
        'applicabledEmployeeStatus',
        'applicabledGender',
        'leaveCreditedType',
        'allowAdditionalLeaveOnJoin',
        'roundOffCreditedLeaves',
        'lapseLeaveYn',
        'creditLeaveIfResignationPendingYn',
        'empHalfDayLeaveRqstYN',
        'empLeaveRqstYN',
        'empMaxRqstTenureType',
        'empMaxNoRqstTenure',
        'empMaxRqstYearType',
        'empMaxNoRqstYear',
        'empMaxRqstMonthType',
        'empMaxNoRqstMonth',
        'empMinLeaveRequiredToRqstType',
        'empMinNoLeaveRequiredToRqst',
        'maxNoContiniousLeaveAllowedType',
        'maxNoContionousLeaveAllowedNo',
        'maxNoLeavesYearlyType',
        'maxNoLeavesYearly',
        'maxNoLeavesMonthlyType',
        'maxNoLeavesMonthly',
        'empBackDtdLeaveYn',
        'empBackDtdLeaveNo',
        'minDaysAdvncLeaveRqstType',
        'minDaysAdvncLeaveRqstNo',
        'empFutureDtdLeaveYn',
        'mngrFutureDtdLeaveYn',
        'hrFutureDtdLeaveYn',
        'mngrBackDtdLeaveYn',
        'mngrBackDtdLeaveNo',
        'hrBackDtdLeaveYn',
        'hrBackDtdLeaveNo',
        'leaveApplctnDocRequiredYn',
        'docRequiredForLeavesNoAbove',
        'raiseLeaveRqstAftrAttdncProcessedYn',
        'restrictLeaveRqstOnPendingResignationYn',
        'restrictLeaveRqstAftrJoiningForSpecicPeriodType',
        'restrictLeaveRqstAftrJoiningForSpecicPeriodDaysNo',
        'excludeAbsentDaysYn',
        'specificEmpStatusLeaveApplicableYn',
        'empStatusProbationYn',
        'empStatusConfirmedYn',
        'empStatusResignedYn',
        'leaveRqstApplicableType',
        'applicableToGenderYn',
        'applicabilityMaleYn',
        'applicabilityFemaleYn',
        'applicabilityOtherYn',
        'enableThisLeaveBirthdayYn',
        'birthdayLeaveAdvanceDays',
        'birthdayLeavePostDays',
        'weddingAnniversaryLeaveYn',
        'weedingAnniversaryLeaveAdvanceDays',
        'weddingAnniversaryLeavePostDays',
        'advanceLeaveBalanceYn',
        'advanceBalanceLimit',
        'blockClubbingWithOtherLeavesYn',
        'leaveTypes',
        'leaveDonationYn',
        'donateLeaveEmpYn',
        'donateLeaveManagerYn',
        'donateLeaveHrYn',
        'maxAnnualLeaveDonation',
        'maxCarryForwardLeavesType',
        'maxCarryForwardLeavesBalance',
        'carryForwardMethod',
        'carryForwardMethodDays',
        'nextYearBalanceUsageOfCrntYearYn',
        'nextYearBalanceUsageOfCrntYearLimit',
        'backdatedLeaveCancellationAfterCarryForwardYn',
        'allowBackdatedLeaveAfterCarryForward',
        'sendCarryForwardAlertYn',
        'noOfDaysToSendAlertBeforeExpiry',
        'alertMessage',
        'includeWeeklyOffAsLeaveYn',
        'includePostLeaveWeeklyOffYn',
        'sandwichLeaveYn',
        'requireAdvanceSubmissionToExcludeWeeklyOffType',
        'advanceSubmissionDaysBeforeToExcludeWeeklyOff',
        'holidaysInLeaveCountYn',
        'includeWeekoffAndHolidayIfSpannedByLeaveYn',
        'requireAdvanceSubmissionToExcludeWeekoffAndHolidayType',
        'advanceSubmissionDaysBeforeToExcludeWeekoffAndHoliday'
    ];
}
